[2025-04-12 20:11:15] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 20:11:15] ErrorException: Undefined array key "APP_ENV" in /var/www/html/core/exception/ExceptionHandler.php on line 102
Stack trace: #0 /var/www/html/core/exception/ExceptionHandler.php(102): App\core\exception\ExceptionHandler::handleError(2, 'Undefined array...', '/var/www/html/c...', 102)
#1 /var/www/html/core/exception/ExceptionHandler.php(86): App\core\exception\ExceptionHandler::renderErrorPage(Object(App\core\Response), 500, 'Server Error', Object(TypeError))
#2 /var/www/html/public/web.php(142): App\core\exception\ExceptionHandler::handle(Object(TypeError))
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 20:12:18] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 20:12:18] ErrorException: Undefined array key "APP_ENV" in /var/www/html/core/exception/ExceptionHandler.php on line 102
Stack trace: #0 /var/www/html/core/exception/ExceptionHandler.php(102): App\core\exception\ExceptionHandler::handleError(2, 'Undefined array...', '/var/www/html/c...', 102)
#1 /var/www/html/core/exception/ExceptionHandler.php(86): App\core\exception\ExceptionHandler::renderErrorPage(Object(App\core\Response), 500, 'Server Error', Object(TypeError))
#2 /var/www/html/public/web.php(142): App\core\exception\ExceptionHandler::handle(Object(TypeError))
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 20:15:01] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 20:15:24] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 20:18:05] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:35:29] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:37:23] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:45:23] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:47:29] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:48:28] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:50:43] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:52:29] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 22:57:06] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 23:02:38] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 23:02:38] ErrorException: Attempt to read property "layout" on null in /var/www/html/core/Router.php on line 79
Stack trace: #0 /var/www/html/core/Router.php(79): App\core\exception\ExceptionHandler::handleError(2, 'Attempt to read...', '/var/www/html/c...', 79)
#1 /var/www/html/core/exception/ExceptionHandler.php(112): App\core\Router->renderView('errors/error', Array)
#2 /var/www/html/core/exception/ExceptionHandler.php(86): App\core\exception\ExceptionHandler::renderErrorPage(Object(App\core\Response), 500, 'Server Error', Object(TypeError))
#3 /var/www/html/public/web.php(142): App\core\exception\ExceptionHandler::handle(Object(TypeError))
#4 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#5 {main}

[2025-04-12 23:06:51] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 23:07:14] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-12 23:07:33] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-13 15:49:51] App\core\exception\DatabaseException: Failed to fetch records: SQLSTATE[2201X]: <<Unknown error>>: 7 ERROR:  OFFSET must not be negative in /var/www/html/repositories/Repository.php on line 85
Stack trace: #0 /var/www/html/controllers/ProductController.php(51): App\repositories\Repository->findAll(Array, false, 'created_at DESC', 12, -12)
#1 [internal function]: App\controllers\ProductController->index(Object(App\core\Request))
#2 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#3 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#4 /var/www/html/public/web.php(137): App\core\Application->run()
#5 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#6 {main}

[2025-04-13 15:50:01] App\core\exception\DatabaseException: Failed to fetch records: SQLSTATE[2201X]: <<Unknown error>>: 7 ERROR:  OFFSET must not be negative in /var/www/html/repositories/Repository.php on line 85
Stack trace: #0 /var/www/html/controllers/ProductController.php(51): App\repositories\Repository->findAll(Array, false, 'created_at DESC', 12, -12)
#1 [internal function]: App\controllers\ProductController->index(Object(App\core\Request))
#2 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#3 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#4 /var/www/html/public/web.php(137): App\core\Application->run()
#5 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#6 {main}

[2025-04-13 15:51:44] App\core\exception\DatabaseException: Failed to fetch records: SQLSTATE[2201X]: <<Unknown error>>: 7 ERROR:  OFFSET must not be negative in /var/www/html/repositories/Repository.php on line 85
Stack trace: #0 /var/www/html/controllers/ProductController.php(51): App\repositories\Repository->findAll(Array, false, 'created_at DESC', 12, -12)
#1 [internal function]: App\controllers\ProductController->index(Object(App\core\Request))
#2 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#3 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#4 /var/www/html/public/web.php(137): App\core\Application->run()
#5 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#6 {main}

[2025-04-13 15:51:58] App\core\exception\DatabaseException: Failed to fetch records: SQLSTATE[2201X]: <<Unknown error>>: 7 ERROR:  OFFSET must not be negative in /var/www/html/repositories/Repository.php on line 85
Stack trace: #0 /var/www/html/controllers/ProductController.php(51): App\repositories\Repository->findAll(Array, false, 'created_at DESC', 12, -12)
#1 [internal function]: App\controllers\ProductController->index(Object(App\core\Request))
#2 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#3 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#4 /var/www/html/public/web.php(137): App\core\Application->run()
#5 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#6 {main}

[2025-04-13 15:52:08] App\core\exception\DatabaseException: Failed to fetch records: SQLSTATE[2201X]: <<Unknown error>>: 7 ERROR:  OFFSET must not be negative in /var/www/html/repositories/Repository.php on line 85
Stack trace: #0 /var/www/html/controllers/ProductController.php(51): App\repositories\Repository->findAll(Array, false, 'created_at DESC', 12, -12)
#1 [internal function]: App\controllers\ProductController->index(Object(App\core\Request))
#2 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#3 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#4 /var/www/html/public/web.php(137): App\core\Application->run()
#5 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#6 {main}

[2025-04-13 15:52:44] App\core\exception\DatabaseException: Failed to fetch records: SQLSTATE[2201X]: <<Unknown error>>: 7 ERROR:  OFFSET must not be negative in /var/www/html/repositories/Repository.php on line 85
Stack trace: #0 /var/www/html/controllers/ProductController.php(51): App\repositories\Repository->findAll(Array, false, 'created_at DESC', 12, -12)
#1 [internal function]: App\controllers\ProductController->index(Object(App\core\Request))
#2 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#3 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#4 /var/www/html/public/web.php(137): App\core\Application->run()
#5 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#6 {main}

[2025-04-13 16:09:42] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-13 16:10:11] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-13 20:16:40] ErrorException: include_once(/var/www/html/views/products/view.php): Failed to open stream: No such file or directory in /var/www/html/core/Router.php on line 93
Stack trace: #0 /var/www/html/core/Router.php(93): App\core\exception\ExceptionHandler::handleError(2, 'include_once(/v...', '/var/www/html/c...', 93)
#1 /var/www/html/core/Router.php(93): include_once()
#2 /var/www/html/core/Router.php(80): App\core\Router->renderViewOnly('products/view', Array)
#3 /var/www/html/core/Controller.php(34): App\core\Router->renderView('products/view', Array)
#4 /var/www/html/controllers/ProductController.php(100): App\core\Controller->render('products/view', Array)
#5 [internal function]: App\controllers\ProductController->view(Object(App\core\Request))
#6 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#7 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#8 /var/www/html/public/web.php(137): App\core\Application->run()
#9 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#10 {main}

[2025-04-13 20:16:44] ErrorException: include_once(/var/www/html/views/products/view.php): Failed to open stream: No such file or directory in /var/www/html/core/Router.php on line 93
Stack trace: #0 /var/www/html/core/Router.php(93): App\core\exception\ExceptionHandler::handleError(2, 'include_once(/v...', '/var/www/html/c...', 93)
#1 /var/www/html/core/Router.php(93): include_once()
#2 /var/www/html/core/Router.php(80): App\core\Router->renderViewOnly('products/view', Array)
#3 /var/www/html/core/Controller.php(34): App\core\Router->renderView('products/view', Array)
#4 /var/www/html/controllers/ProductController.php(100): App\core\Controller->render('products/view', Array)
#5 [internal function]: App\controllers\ProductController->view(Object(App\core\Request))
#6 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#7 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#8 /var/www/html/public/web.php(137): App\core\Application->run()
#9 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#10 {main}

[2025-04-13 20:34:59] ErrorException: Undefined variable $newArrivals in /var/www/html/views/home/index.php on line 61
Stack trace: #0 /var/www/html/views/home/index.php(61): App\core\exception\ExceptionHandler::handleError(2, 'Undefined varia...', '/var/www/html/v...', 61)
#1 /var/www/html/core/Router.php(93): include_once('/var/www/html/v...')
#2 /var/www/html/core/Router.php(80): App\core\Router->renderViewOnly('home/index', Array)
#3 /var/www/html/core/Controller.php(34): App\core\Router->renderView('home/index', Array)
#4 /var/www/html/controllers/SiteController.php(32): App\core\Controller->render('home/index', Array)
#5 [internal function]: App\controllers\SiteController->home(Object(App\core\Request))
#6 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#7 /var/www/html/core/Application.php(85): App\core\Router->resolve()
#8 /var/www/html/public/web.php(137): App\core\Application->run()
#9 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#10 {main}

[2025-04-14 13:21:41] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-14 13:22:36] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-14 13:37:19] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#2 /var/www/html/public/web.php(137): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-14 13:43:28] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, class App\controllers\VendorController does not have a method "updateOrderStatus" in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(Array, Object(App\core\Request))
#1 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#2 /var/www/html/public/web.php(139): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-14 13:45:47] ParseError: syntax error, unexpected token "public", expecting end of file in /var/www/html/controllers/VendorController.php on line 729
Stack trace: #0 /var/www/html/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/v...')
#1 /var/www/html/core/Router.php(63): Composer\Autoload\ClassLoader->loadClass('App\\controllers...')
#2 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#3 /var/www/html/public/web.php(139): App\core\Application->run()
#4 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#5 {main}

[2025-04-14 13:45:55] ParseError: syntax error, unexpected token "public", expecting end of file in /var/www/html/controllers/VendorController.php on line 729
Stack trace: #0 /var/www/html/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/var/www/html/v...')
#1 /var/www/html/core/Router.php(63): Composer\Autoload\ClassLoader->loadClass('App\\controllers...')
#2 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#3 /var/www/html/public/web.php(139): App\core\Application->run()
#4 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#5 {main}

[2025-04-14 14:11:48] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#2 /var/www/html/public/web.php(139): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

[2025-04-14 14:12:32] TypeError: call_user_func(): Argument #1 ($callback) must be a valid callback, no array or string given in /var/www/html/core/Router.php on line 74
Stack trace: #0 /var/www/html/core/Router.php(74): call_user_func(false, Object(App\core\Request))
#1 /var/www/html/core/Application.php(63): App\core\Router->resolve()
#2 /var/www/html/public/web.php(139): App\core\Application->run()
#3 /var/www/html/public/index.php(2): require_once('/var/www/html/p...')
#4 {main}

